[package]
name = "chess_like"
version = "0.2.2"
authors = ["Ozaren <krishna.sd.2012@gmail.com>"]

[dependencies]
piston = "*"
piston_window = "*"
pistoncore-glutin_window = "*"
piston2d-opengl_graphics = "*"
piston2d-graphics = "*"
piston2d-gfx_graphics = "*"
gfx_device_gl = "*"