[package]
name = "chess_like"
version = "0.1.0"
authors = ["Ozaren <krishna.sd.2012@gmail.com>"]

[dependencies]
piston = "0.36.0"
piston2d-graphics = "0.26.0"
pistoncore-glutin_window = "0.46.0"
piston2d-opengl_graphics = "0.53.0"